# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title_bar: Josh Abrams - Development Blog
title: Josh Abrams
email: joshua.a.abrams@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hello and welcome to my newly re-designed devlopment blog. Please
  note that I have decided to scrap my original design and most of the
  associated articles.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://frizzbolt.github.io" # the base hostname & protocol for your site
twitter_username: frizzbolt
github_username: frizzbolt
under_construction: false

# Build settings
markdown: kramdown
